services:
  node:
    image: node:alpine
    volumes:
      - ./:/var/www/
    working_dir: /var/www/
    tty: true
    command: npm start
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.checkout_tarde_app.tls=true"
      - "traefik.http.routers.checkout_tarde_app.tls.certresolver=cloudflare"
      - "traefik.http.routers.checkout_tarde_app.entrypoints=websecure"
      - "traefik.http.routers.checkout_tarde_app.rule=Host(`checkout-tarde.local.rpopuc.com`)"
      - "traefik.http.services.checkout_tarde_app.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik"
    networks:
      - traefik

networks:
  traefik:
    external: true
